#!/usr/bin/env node
/*
 * Build data/seed.js (the dataset a first-time visitor sees) from the sibling projects:
 *   - MONICA export JSON  (../monica-npi-chart/tools/Monica-Input-Output-plan-export-20260602.json)
 * plus DEMO employees, assignments and trips (made-up names - replace them with the real roster).
 *
 * (Gen12 Excel tasks are not in the demo: import them into "Gen12 AMD" from 設定 → 資料.)
 *   node tools/build_seed.js [monica.json]
 */
const fs = require("fs");
const path = require("path");
const Convert = require("../js/convert.js");

const root = path.join(__dirname, "..");
const monicaPath = process.argv[2] || path.join(root, "../monica-npi-chart/tools/Monica-Input-Output-plan-export-20260602.json");

// Deterministic pseudo-random, so the seed does not change between runs.
let rs = 20261004;
const rnd = () => ((rs = (rs * 1103515245 + 12345) % 2147483648) / 2147483648);

const data = Convert.emptyData();
const NAMES = ["Alex", "Bella", "Chris", "Daisy", "Ethan", "Fiona", "George", "Hannah", "Ivan", "Julia", "Kevin", "Lily", "Max"];
data.employees = NAMES.map((n, i) => ({ id: "e" + String(i + 1).padStart(2, "0"), name: n + "（示範）", active: true }));

// MONICA
const monica = Convert.monicaItems(JSON.parse(fs.readFileSync(monicaPath, "utf8")));
Convert.mergePhases(data, monica.phases);
// Use the dashboard's palette for the phases (MONICA's are neon test colors).
const PH = ["#2a78d6", "#4a3aa7", "#1baf7a", "#eda100", "#e87ba4"];
data.settings.phases.forEach((p, i) => (p.color = PH[i % PH.length]));
const mres = Convert.apply(data, Convert.plan(data, "monica", monica.items));


// Stable ids (the generator ids contain a timestamp).
const idMap = new Map();
const reId = (prefix, list) => list.forEach((x, i) => idMap.set(x.id, (x.id = prefix + String(i + 1).padStart(3, "0"))));
reId("j", data.projects);
reId("f", data.pfams);
reId("t", data.tasks);
for (const f of data.pfams) f.projectId = idMap.get(f.projectId);
for (const t of data.tasks) t.pfamId = idMap.get(t.pfamId);
data.projects.forEach((p, i) => (p.color = Convert.PALETTE[i % Convert.PALETTE.length]));

// DEMO assignments: each PFAM has an owner (one person runs all its phases); some tasks get a helper,
// and a few PFAMs stay unassigned so the "未指派" list has something to show.
const emp = data.employees.map((e) => e.id);
data.pfams.forEach((f, i) => {
  const unassigned = rnd() < 0.12;
  const owner = emp[i % emp.length];
  for (const t of data.tasks.filter((x) => x.pfamId === f.id)) {
    if (unassigned) continue;
    t.assignees = [owner];
    if (rnd() < 0.2) t.assignees.push(emp[Math.floor(rnd() * emp.length)]);
    t.assignees = [...new Set(t.assignees)];
  }
});
// DEMO completion: most past tasks are done, a few are overdue.
const today = "2026-10-04";
for (const t of data.tasks) {
  t.done = t.end < today && rnd() < 0.85;
}

// DEMO trips across 2026.
const LOC = ["MX", "MX", "LZ", "CZ", "LZ", "MX", "TN"];
const PURPOSE = ["Pilot build 支援", "MFG test bring-up", "Golden rack 驗證", "BSL 測試支援", "客戶稽核", "Volume build 支援"];
const day = (iso) => Date.UTC(+iso.slice(0, 4), +iso.slice(5, 7) - 1, +iso.slice(8, 10));
const iso = (ms) => new Date(ms).toISOString().slice(0, 10);
let tn = 0;
for (let k = 0; k < 26; k++) {
  const e = emp[Math.floor(rnd() * emp.length)];
  const startMs = day("2026-01-05") + Math.floor(rnd() * 360) * 86400000;
  const len = 4 + Math.floor(rnd() * 14);
  const proj = data.projects[Math.floor(rnd() * data.projects.length)];
  data.trips.push({
    id: "r" + String(++tn).padStart(3, "0"),
    empId: e,
    start: iso(startMs),
    end: iso(startMs + (len - 1) * 86400000),
    location: LOC[Math.floor(rnd() * LOC.length)],
    purpose: PURPOSE[Math.floor(rnd() * PURPOSE.length)],
    projectId: proj.id,
    notes: "",
  });
}
data.trips.sort((a, b) => a.start.localeCompare(b.start));
data.source = { demo: true, builtAt: new Date().toISOString().slice(0, 19), monica: path.basename(monicaPath) };

const out = path.join(root, "data/seed.js");
fs.writeFileSync(out, "// Generated by tools/build_seed.js - do not edit by hand. Employees, assignments and trips are DEMO data.\nwindow.LLT_SEED = " + JSON.stringify(data) + ";\n");
console.log(`MONICA: +${mres.added} tasks, ${mres.projects} projects, ${mres.pfams} PFAMs`);
console.log(`total : ${data.projects.length} projects, ${data.pfams.length} PFAMs, ${data.tasks.length} tasks, ${data.employees.length} employees, ${data.trips.length} trips -> ${path.relative(root, out)}`);
